oro_bug:
    resource: "@OroBugBundle/Controller"
    type: annotation

inventory:
    resource: "@InventoryBundle/Controller"
    type: annotation

inventory_api_vehicle:
    resource:     "@InventoryBundle/Controller/Api/Rest/VehicleController.php"
    type:         rest
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        _controller: OroDashboardBundle:Dashboard:view

oro_auto_routing:
    resource: .
    type:     oro_auto
