datagrid:
    issues-grid:
        source:
            acl_resource: bug.issue_view
            type: orm
            query:
                select:
                    - i.id
                    - i.code as code
                    - i.summary as summary
                    - type_entity.id as type
                    - priority_entity.label as priority
                    - status_entity.label as status
                    - resolution_entity.label as resolution
                    - reporter_entity.username as reporter
                    - assignee_entity.username as assignee
                    - i.created
                    - i.updated
                from:
                    - { table: OroBugBundle:Issue, alias: i}
                join:
                    left:
                        - { join: i.priority, alias: priority_entity}
                        - { join: i.status, alias: status_entity}
                        - { join: i.resolution, alias: resolution_entity}
                        - { join: i.owner, alias: reporter_entity}
                        - { join: i.assignee, alias: assignee_entity}
                        - { join: i.type, alias: type_entity}
        columns:
            code:
                label: oro.bug.issue.code.label
            summary:
                label: oro.bug.issue.summary.label
            type:
                type: twig
                label: oro.bug.issue.type.label
                frontend_type: html
                template: OroBugBundle:Datagrid:issueType.html.twig
            priority:
                label: oro.bug.issue.priority.label
            status:
                label: oro.bug.issue.status.label
            resolution:
                label: oro.bug.issue.resolution.label
            reporter:
                label: oro.bug.issue.reporter.label
            assignee:
                label: oro.bug.issue.assignee.label
            created:
                label: oro.bug.issue.created.label
                frontend_type: date
            updated:
                label: oro.bug.issue.updated.label
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: bug.issue_update
                params:
                    - id
            view_link:
                type: url
                route: bug.issue_view
                params:
                    - id
            delete_link:
                type: url
                route: bug_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                code:
                    data_name:
                        i.code
        filters:
            columns:
                reporter:
                    type: string
                    data_name: i.owner
                updated:
                    type: date
                    data_name: i.updated
                created:
                    type: date
                    data_name: i.created
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  bug.issue_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  bug.issue_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  bug.issue_delete