placeholders:
    view_content_data_additional_information:
        items:
            oro_bug_user_issues: ~
    view_navButtons_before:
        items:
            oro_bug_user_create_issue: ~
items:
    oro_bug_user_issues:
        template: OroBugBundle:Placeholders:issues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: bug.issue_view

    oro_bug_user_create_issue:
        template: OroBugBundle:Placeholders:createIssue.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: bug.issue_view
