parameters:
#    oro_bug.example.class: Oro\BugBundle\Example

services:
    bug.issue_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - Oro\BugBundle\Entity\Issue
            - "@doctrine.orm.entity_manager"

    bug.form.type.select.user:
        class: BugBundle\Form\Type\UserSelectType
        tags:
            - { name: form.type, alias: bug_select_user }

    bug.form.type.select.issueResolution:
        class: Oro\BugBundle\Form\Type\IssueResolutionSelectType
        tags:
            - { name: form.type, alias: bug_select_issue_resolution }

    bug.form.type.select.issuePriority:
        class: Oro\BugBundle\Form\Type\IssuePrioritySelectType
        tags:
            - { name: form.type, alias: bug_select_issue_priority }

    bug.form.type.select.issueStatus:
        class: Oro\BugBundle\Form\Type\IssueStatusSelectType
        tags:
            - { name: form.type, alias: bug_select_issue_status }

    bug.form.type.select.issue:
        class: Oro\BugBundle\Form\Type\IssueSelectType
        tags:
            - { name: form.type, alias: bug_select_issue }


    bug.form.type.select.issueType:
        class: Oro\BugBundle\Form\Type\IssueTypeSelectType
        arguments: [@translator]
        tags:
            - { name: form.type, alias: bug_select_issue_type }

    bug.form.type.issue.children:
        class: Oro\BugBundle\Form\Type\ChildrenIssueType
        tags:
            - { name: form.type, alias: bug_children_issue }

    bug.form.type.issue.parent.select:
        class: Oro\BugBundle\Form\Type\ParentIssueSelectType
        tags:
            - { name: form.type, alias: bug_parent_issue_select }

    bug.form.type.issue:
        class: Oro\BugBundle\Form\Type\IssueType
        tags:
            - { name: form.type, alias: bug_issue }

    bug.form.type.issue.api:
        class: Oro\BugBundle\Form\Type\IssueApiType
        tags:
            - { name: form.type, alias: bug_issue_api }

    bug.form.handler.issue:
        class: Oro\BugBundle\Form\Handler\IssueHandler
        scope: request
        arguments:
            - @bug.form.type.issue
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bug.form.handler.issue.api:
        class: Oro\BugBundle\Form\Handler\IssueHandler
        scope: request
        arguments:
            - @bug.form.type.issue.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bug.data.convererter:
        class: Oro\BugBundle\Services\DataConverter





